kvm-bindings: allow confusable_idents
Currently, CI is broken due to the following error:

  error: found both `ẕ1` and `ẕl` as identifiers, which look alike
      --> kvm-bindings/src/x86_64/bindings.rs:1199:9
       |
    91 |     derive(zerocopy::IntoBytes, zerocopy::Immutable, zerocopy::FromBytes)
       |                                                      ------------------- other identifier used here
  ...
  1199 |     pub l: __u8,
       |         ^ this identifier can be confused with `ẕ1`
       |
       = note: `-D confusable-idents` implied by `-D warnings`
       = help: to override `-D warnings` add `#[allow(confusable_idents)]`

This is due to a mixture bindgen-generated code and derive
macro-generated code. Since none of this is human generated, just like
most of kvm-bindings, turn the lint off for the crate.

Signed-off-by: Carlos López <clopez@suse.de>